### ISSUE TITLE
DST bug?

### ISSUE THREAD

**Issue by pmyteh** [dreeves/tminder#1]
The UK moved to DST this morning, and this evening I find tminder's time to go calculations are off by an hour. Intriguingly, though, it only applies to target times from midnight onwards, not for 23:59 or earlier this evening:

![screenshot - 290315 - 23 27 30](https://cloud.githubusercontent.com/assets/890868/6888112/46fab112-d66b-11e4-87f7-b03d3f923a97.png)
as against:
![screenshot - 290315 - 23 27 54](https://cloud.githubusercontent.com/assets/890868/6888113/46fc5d0a-d66b-11e4-829f-a3febf91460f.png)

For all times from midnight onward, the time calculated is one hour greater than reality.

I've had a look through the source and I can't find any obvious timezone conversions, so it seems like it really ought to be using local time throughout (I'm set to Europe/London, which is +0100 just now). This leaves me slightly puzzled, as the DST shift shouldn't matter in that case. Perhaps something in the recent updates is responsible?

My system is running Debian Linux; the issue applies with both Chrome and Firefox.

**Comment by dreeves** [comment]
I had the same issue! But only on the day (or day after, I can't recall) of the DST switch (earlier this month for me, in the US). Can you confirm that the problem fixes itself tomorrow?

Thanks so much for reporting this. I bet the explanation will turn out to be super interesting, since, as you say, the code just uses localtime.

**Comment by pmyteh** [comment]
Yes - working fine today.

**Comment by dreeves** [comment]
This now intentionally ignores DST and computes strictly based on the generic time of day. For example, if it's 9pm on the night the clocks will change and you specify a deadline of 9am it will treat that as 12 hours away, even though it won't really be, according to the crazy clocks.

But you can now specify, e.g., "9am - 1h" or "9am + 1h" as the deadline and it will do the arithmetic for you.
